version: "3.6"
services:
  webproxy:
    image: traefik:1.5
    command:
      - "--api"
#      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
#      - "--entrypoints=Name:https Address::443 TLS"
#      - "--defaultentrypoints=http,https"
#      - "--acme"
#      - "--acme.storage=/etc/traefik/acme/acme.json"
#      - "--acme.entryPoint=https"
#      - "--acme.httpChallenge.entryPoint=http"
#      - "--acme.OnHostRule=true"
#      - "--acme.onDemand=false"
#      - "--acme.email=contact@mydomain.ca"
#      - "--docker"
      - "--docker.swarmmode"
      - "--docker.domain=butt.nz"
      - "--docker.exposedbydefault=false"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/etc/traefik/acme:rw
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - web

volumes:
  traefik-acme:

networks:
  web:
    external: true
  ssb:
    attachable: true
